### ISSUE TITLE
Button ellipses affect all buttons

### ISSUE THREAD

**Issue by darth-cheney** [dkrasner/Simpletalk#68]
The new ellipses on Button labels is affecting all buttons regardless of their layout or intended width. See the save button in Script Editor for an example.
  
We should make sure that ellipses only appear in buttons with a specific designated width.

**Comment by dkrasner** [comment]
I believe all buttons now have a designated width, so unless we want to allow for   The issue with the 'save button' was that it did not specify its width property properly (see #72 )
