### ISSUE TITLE
Some properties are not preserved on de-serialization

### ISSUE THREAD

**Issue by dkrasner** [dkrasner/Simpletalk#84]
### Main Points ###

There are a number of properties which are not preserved by our de-serialization process. 

`wants-move`   The easiest way to test this is to add a part, set "wants-move" to true, serialize and load. You will see the property properly set in the editor but no effect. Toggling it will bring the effect back, as expected. 

Similarly for "allow-scrolling" as demonstrated by the two screenshots below. First is before serialization, 2nd is after:

![Screen Shot 2021-08-31 at 2 37 53 PM](https://user-images.githubusercontent.com/1154326/131504728-45a517f2-64e9-4bae-af17-77feffc2e653.png)

![image](https://user-images.githubusercontent.com/1154326/131504870-f968aa50-4010-4918-b6bd-76afa1484f6e.png)

**Comment by darth-cheney** [comment]
@dkrasner I have had  a fix to the `allow-scrolling` case in my working branch. It should be good once I merge in the language stack. See this commit and its message: https://github.com/dkrasner/Simpletalk/commit/7d69edb4f7e2458ac12adf7256b58cab23deb4ab
